language: node_js

node_js:
  - stable

install: npm install

script:
  - npm run cover
  
deploy:
  provider: npm
  script:
  - "./check-package-version.sh"
  email: alexis@sgarbossa.com.ar
  api_key:
    secure: Ms+PpRXtlOR/Zpd5P9aOG3m2RhjYqDDZgST+0fzP8HdF4iBBLMGAQ/rFBtXxt78fS4U2Yse7HTlpHv9bCofShbtRBHdep1ple+l71QwlVG257ZErU/osljbxB4n7OznA+I5koWGxIugI0mS87sXAqHlNOKm98+V3ctlngdE3LBk0DK5M1gxXcfMnzKqjOhliEt0pI0kcQhcvzCwgqSOkb8F08u2iZXK/DXFgTdGZQCUY04bRow25u0EsdFdRKEBQoHYxEqScdjRwUQEhohF7+nLwGk3qfAmDk1o+85f3ZtxvI3AR6EEzogK0cBoQPtulOSiSPmcHRe95R2jJx0J4225GRyIQFv5tX6uQFGSPP2XBiKGHmuJq62tY28dGxi0jqC/mBJTODoJgAQuHmpCRyCqLCEy+0WHQSp/9VQ7cj4DHxU6oIh622emR2RFb19k2BjluIGb9FGPsOa9HPwsOtZRXkA5+5hKO/4bJIaUKkbmV5kQUt3Z7hOeSDKZgcTgMjc5cece9Y71zgL1VqfrDFXz/cqkz8441YBMW4KNRBU5Au0LY1+OgvmpsSR74ZlvIk+Dkt2/JziEwVXkouD0Bw+TosIgCNx8etWUapOO0dolvSd2CXWylY2EKVWufK7rJWoAt+OmZ9xqz8EXQAffGtLI2TRFInb6DNmrp4DsCDyA=
  on:
    all_branches: true
