language: node_js
node_js:
- stable
install: npm install
script:
- npm run cover
- ./check-package-version.sh
deploy:
  provider: npm
  email: alexis@sgarbossa.com.ar
  api_key:
    secure: nLMXlifMRcTgKV6umlMUYsDKMfqLpdlJeAoGDeRoT4Pg2pAByI6mJKUzOexFzr/Q+UruNWeCQDsRGSyAilSPXzxfqNr1aOt2/p1M08738uAkI1+iJBRK55nXsPeW+7q6wFRgpJTXl0v9Dle3kD0mC2fSYTjCDdI5lD9Onuw6V78IGlOLvRXGuiJoy8EC6tUS2VPJaMdp6+PKT8JAJ++UThggbnXZZ2jnMiVi6jReAgiuVKobGOwPyKQ5Pvh9nbx47KB+7By7zI04TeLH9VpjZRKiSgRX4AtKNm9exhnTIAYeh+M56Sv8QfKcAs9/fAqa5eQDGBJB/CVXfoSfyN/GrFycKTGIZslfyoslCoPioztPU0Okl/wLhugZxhxzcex+oczoUh59JKkfnTfTCkOTymwWLxRjy5IjBZU+7aQwqXA2eLk/n/bfR6R5JRCECbwTpggMvA6G6UomEE2a7N8azyf0OJSxo5fZSMwRi7DPI0FMQg6h6qY7FfRa0zd9tLx3sTzDW7su7yD7g8aW4skv9G19/qea7TTVvKg6gJa8PPiRC/rVVEcw0LuDNd8lknA06PhueoZuZvt258F1YNqeEYwBjZH/Y5jFRjcSLdpOpVQorDiarNgAyzJ1rS0BhUB5+y9v5XqtLDryce1GE5NDVEkLTDkdpO4yuPU3G0vILOM=
  on:
    repo: baires/npm-module-boilerplate
